### ISSUE TITLE
download file with spaces into filename

### ISSUE THREAD

**Issue by antoniorv75** [Alfresco/alfresco-docker-installer#142]
Good afternoon.
I wondering if someone has the same problem than I am having downloading documents?, I am trying download a file with the repository browser ACS. Example **a filename called "Hi there.docx" will be downloaded as "Hi+there.docx".** 
However When I upload the file, the file is showed with the name perfectly into the ACS interface, the problem occurs when you download the file, something changes the spaces by '+'

Any ideas?
Thank you in advance.
Kind regards.

**Comment by aborroy** [comment]
I guess you need to upgrade your deployment, that was fixed in:
https://github.com/Alfresco/alfresco-community-repo/pull/870

**Comment by antoniorv75** [comment]
> I guess you need to upgrade your deployment, that was fixed in: [Alfresco/alfresco-community-repo#870](https://github.com/Alfresco/alfresco-community-repo/pull/870)

I checked the last version and the other ones too just in case only to detect what could be the version where this problem starts. 
With 7.2 and forward seem the problem persists inspite of https://github.com/Alfresco/alfresco-community-repo/pull/870 indicates the patch is applied already.. it's curious from 7.2 backwards this behaviours is not occurs. The patch is not applied apparentely, i really don't know if the team are aware about that, because this seem a problem really easy to solve. When you try download a file it not runs but if you try view in browser, the file is downloaded perfectly, that's very curious.

Thank you for your time @aborroy

**Comment by aborroy** [comment]
Can you try using these versions?

ALFRESCO_CE_TAG=7.2.0.1
SHARE_TAG=7.2.0.2

**Comment by antoniorv75** [comment]
Yes, it's a pity, the problem still occurs. :(

**Comment by aborroy** [comment]
I've create this patch to solve the problem:
https://github.com/aborroy/mnt-22668

Let me know if that helps.

**Comment by aborroy** [comment]
You're right

**Comment by antoniorv75** [comment]
Puff, the problem persist, if I check with your docker-installer quicky following the 7.2 version, I found the same problem.
The amp file is installed under .../alfresco/modules/amps and I run the docker-compose up --build -d 
Everything run fine but when I try to download from : http://<urlserver>/share/page/site/swsdp/documentlibrary#filter=path%7C%2FMeeting%2520Notes%7C&page=1 and I make click into different files in some of them the problem persists in two files, but not in other one.... this is curious.
![image](https://user-images.githubusercontent.com/58980048/179222972-0e0880ca-3a22-41f2-af32-6822490814e6.png)

![image](https://user-images.githubusercontent.com/58980048/179222860-35804698-f887-4de8-a379-62f84f48425f.png)

**Comment by aborroy** [comment]
That might be related with Browser cache. May you try with a different browser or using incognito mode?

**Comment by antoniorv75** [comment]
Hi @aborroy , It works!, the problem was the cache.
Thank you very much, I hope this patch with be merged with the next release, if not I shouldn't update until it would be ready.
